package de.digitalemil.eagle;

public abstract class Types {
	public final static int PART = 0, BONE = 1,RECTANGLE = 2,QUAD = 3,THING = 4,ELLIPSE = 15,TRIANGLE = 28, TEXQUAD= 30, IMAGE= 3,
			BOUNDINGCIRCLE = 25, PARTANIMATION = 6,COMPOSITEANIMATION = 7, LOOP= 83, THINGCONTAINER= 84, LAKOTAANIMATION = 85, TEXT = 112;
}